version: 2
jobs:
 build:
   machine: true
   steps:
     - checkout 

     # build image
     - run: |         
         docker info
         docker build -t aspnetapp -f Dockerfile .

     # deploy the image
     - run: |         
         docker login --username=$pinaki.best@gmail.com --password=$fd9bf615-10fb-4da1-beb7-a757f6146d54 registry.heroku.com
         docker tag aspnetapp registry.heroku.com/$pinakidotnetcore/web
         docker push registry.heroku.com/$pinakidotnetcore/web                
         curl https://cli-assets.heroku.com/install.sh | sh
         heroku container:release web -a $pinakidotnetcore
